[package]
name = "ktrl"
version = "0.1.3"
authors = ["Itay Garin <thifixp@gmail.com>"]
description = "A Supercharged Keyboard Programming Daemon"
keywords = ["cli", "linux", "daemon", "keyboard", "layout"]
categories = ["command-line-utilities"]
homepage = "https://https://github.com/ItayGarin/ktrl"
repository = "https://https://github.com/ItayGarin/ktrl"
documentation = "https://https://github.com/ItayGarin/ktrl"
readme = "README.md"
license = "GPL-3.0"
edition = "2018"

[dependencies]
evdev-rs = "0.4.0"
uinput-sys = "0.1.7"
libc = "0.2.70"
lazy_static = "1.4.0"
inner = "0.1.1"
serde = "1.0.110"
ron = "0.6.0"
clap = "2.33.1"
log = "0.4.8"
simplelog = "0.8.0"
nix = "0.17.0"
zmq = "0.9.2"
rodio = {version = "0.11.0", optional = true}
enum-iterator = {version = "0.6.0", optional = true}

[features]
sound = ["rodio", "enum-iterator"]
